services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: portofolio-webApp
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "8088:80"
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  laravel:
    driver: bridge