apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate-job
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: 0nlyb/laravel-minikube-demo:latest
        command: ["php", "artisan", "migrate", "--force"]
      restartPolicy: Never
